[project]
name = "backend"
version = "0.1.0"
description = "Backend for Motion by Aiselu - Physiotherapy dictation app"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=1.4.1",
    "linkup-sdk>=0.2.7",
    "load-dotenv>=0.1.0",
]
